### PR TITLE
Feature/ro gh3 csv out

### LINKED ISSUE #3: chkmd: generate CSV report with output for our supported MD fields
DEPENDS ON: chkmd: support all tags from our example/template spreadsheet/md for dummies guide.

We want to be able to send a report back with information about what metadata (that we support/require) each file actually has. So we need to be able to generate spreadsheets to email back to them.

```go
	csvHeader = []struct{
		"Path",
		"Status",
		"Reason",
		"NASA ID",
		"Title",
		"508 Description",
		"Description",
		"Date Created",
		"Location",
		"Keywords",
		"Media Type",
		"File Format",
		"Center",
		"Secondary Creator Credit",
		"Photographer",
		"Album",
	}
```

### PR DESCRIPTION
**Pull request by reedobrien**
This is ready for review @shentonfreude @charlescbeebe 

Check it out and run the tests:
```
git clone <to your gopath>
go get ./...
go test -race ./...
```
Fixes #3 

**NB:** There is a data race in TestMain. You can see it in by running `go test -v -race ./...`. However I am not owrried about it as testing for both possible outcomes works for us in this case. We don't care that the tests is non deterministic because there are only 2 possible outcomes and we test that it is one or the other.

### CODE REVIEW

**Comment by charlescbeebe** [comment]
@reedobrien tests failed for me on b1f93a0:
```
2015/05/12 13:57:36 &main.statistics{Total:113, Relevant:2, Reject:1, Accept:1}
main_test.go:403:

	got: false

	want: true

--- FAIL: TestMain (0.17 seconds)
FAIL
coverage: 91.5% of statements
FAIL	github.com/v-studios/chkmd	1.379s
```

**Comment by reedobrien** [comment]
Do you have exiftool installed? What version?

I'll dig up a mac and see if it fails for me on there.

Reed O'Brien
V! Studios/NASA WESTPrime
☏ 703-760-0440 x110
✆  415-562-6797
✉  reed@v-studios.com

**Comment by reedobrien** [comment]
I installed exiftol 9.95 from http://www.sno.phy.queensu.ca/~phil/exiftool/index.html with the dmg and cloned this repo, checked out this branch. And it passes. Chris?

**Comment by shentonfreude** [comment]
Had to buy a clue from Reed on how to build/run the branch, but the test failed for me as well. I've got exiftool, see last line.

```shell
★ chris@Vampyre:chkmd$ git branch 
  develop
* feature/ro-gh3-csv_out
  master
★ chris@Vampyre:chkmd$ go build .
★ chris@Vampyre:chkmd$ echo $GOPATH
/Users/chris/Projects/go
★ chris@Vampyre:chkmd$ go install .
★ chris@Vampyre:chkmd$ go test -race .
==================
WARNING: DATA RACE
Write by goroutine 34:
  sync.raceWrite()
      /usr/local/go/src/pkg/sync/race.go:41 +0x35
  sync.(*WaitGroup).Wait()
      /usr/local/go/src/pkg/sync/waitgroup.go:122 +0x176
  github.com/v-studios/chkmd.main()
      /Users/chris/Projects/go/src/github.com/v-studios/chkmd/main.go:465 +0x84a
  github.com/v-studios/chkmd.TestMain()
      /Users/chris/Projects/go/src/github.com/v-studios/chkmd/main_test.go:388 +0x128
  testing.tRunner()
      /usr/local/go/src/pkg/testing/testing.go:422 +0x10f

Previous read by goroutine 44:
  sync.raceRead()
      /usr/local/go/src/pkg/sync/race.go:37 +0x35
  sync.(*WaitGroup).Add()
      /usr/local/go/src/pkg/sync/waitgroup.go:60 +0xbe
  github.com/v-studios/chkmd.func·003()
      /Users/chris/Projects/go/src/github.com/v-studios/chkmd/main.go:459 +0x52

Goroutine 34 (running) created at:
  testing.RunTests()
      /usr/local/go/src/pkg/testing/testing.go:504 +0xb46
  testing.Main()
      /usr/local/go/src/pkg/testing/testing.go:435 +0xa2
  main.main()
      github.com/v-studios/chkmd/_test/_testmain.go:83 +0xdc

Goroutine 44 (running) created at:
  github.com/v-studios/chkmd.main()
      /Users/chris/Projects/go/src/github.com/v-studios/chkmd/main.go:461 +0x802
  github.com/v-studios/chkmd.TestMain()
      /Users/chris/Projects/go/src/github.com/v-studios/chkmd/main_test.go:388 +0x128
  testing.tRunner()
      /usr/local/go/src/pkg/testing/testing.go:422 +0x10f
==================
2015/05/13 10:29:20 &main.statistics{Total:141, Relevant:2, Reject:1, Accept:1}
main_test.go:403:

	got: false

	want: true

--- FAIL: TestMain (0.19 seconds)
FAIL
FAIL	github.com/v-studios/chkmd	1.530s
★ chris@Vampyre:chkmd$ which exiftool
/usr/local/bin/exiftool

★ chris@Vampyre:chkmd$ exiftool -ver
9.76
★ chris@Vampyre:chkmd$ go version
go version go1.3.1 darwin/amd64
★ chris@Vampyre:chkmd$ git br -v
  develop                20b0745 [behind 4] Add test for processFiles.
* feature/ro-gh3-csv_out b1f93a0 Add both possible outcomes and compare with OR.
  master                 20b0745 Add test for processFiles.
★ chris@Vampyre:chkmd$ 
```

**Comment by reedobrien** [comment]
not sure what versions charles has, but maybe you both have go 1.3 and that is exposing that race without the verbose flag. I noted it in the issue this PR is for and pulled it over from the gh4 branch. This fixes seeing it with the -v flag for me too. Try again at your leisure @shentonfreude @charlescbeebe. The branch should be at 7b94529 now.

```shell
θ63° [robrien:~/go/src/github.com/v-studios/chkmd] feature/ro-gh3-csv_out+ ± exiftool -ver
9.90
θ64° [robrien:~/go/src/github.com/v-studios/chkmd] feature/ro-gh3-csv_out+ ± go version
go version go1.4.2 linux/amd64
θ65° [robrien:~/go/src/github.com/v-studios/chkmd] feature/ro-gh3-csv_out+ ± git br -v
* feature/ro-gh3-csv_out             7b94529 index on feature/ro-gh4-separate_md_sources: 095d2e8 Remove a race.
```

**Pull request closed without merging**
